#
version: '3.6'

services:
  hugo:
    build:
      context: https://github.com/asperitus/docker-hugo.git
      dockerfile: Dockerfile
    image: asperitus/hugo:latest
    restart: always
    volumes:
      - ./:/www
    ports:
      - "1313:1313"
    entrypoint:
      - '/bin/hugo'
      - 'server'
      - '--bind=0.0.0.0'
      - '-D'
      - '-w'
##
