#
version: '3.6'

services:
  hugo:
    build:
      context: https://github.com/asperitus/docker-hugo.git
      dockerfile: Dockerfile
    image: asperitus/hugo:latest
    restart: always
    volumes:
      - ./:/www
    ports:
      - "1313:1313"
    entrypoint:
      - '/bin/hugo'
      - 'server'
      - '--bind=0.0.0.0'
      - '--baseURL=https://www.local.dhnt.io/'
      - '--appendPort=false'
      - '--buildDrafts'
      - '--buildExpired'
      - '--buildFuture'
      - '--watch'
    labels:
      - traefik.backend=hugo
      - traefik.enable=true
      - traefik.frontend.rule=Host:hugo.local.dhnt.io,www.local.dhnt.io,local.dhnt.io
      - traefik.frontend.passHostHeader=true
      - traefik.backend.loadbalancer.stickiness=false
      - traefik.docker.network=web
      - traefik.port=1313

networks:
  default:
    external: true
    name: web
##
